name: test_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_bloc: ^8.1.6
  bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.2.1
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  draggable_scrollbar: ^0.1.0
  flutter_reorderable_list: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

